// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoeKIibLVYaIKS4dqIuwD8sf16U51gpuE',
    appId: '1:700781686455:web:10a9f56e98ad9a6766e732',
    messagingSenderId: '700781686455',
    projectId: 'cityscan-8aed3',
    authDomain: 'cityscan-8aed3.firebaseapp.com',
    storageBucket: 'cityscan-8aed3.firebasestorage.app',
    measurementId: 'G-P9KT23136W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtnwIMS-WyuHMJ54SnVCvouE5W-m-3NO0',
    appId: '1:700781686455:android:1064cbd6ebb67bc066e732',
    messagingSenderId: '700781686455',
    projectId: 'cityscan-8aed3',
    storageBucket: 'cityscan-8aed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4RMKIiwCIFep5KUglDIYeOIZYLhLNtU',
    appId: '1:700781686455:ios:282464bc363d421d66e732',
    messagingSenderId: '700781686455',
    projectId: 'cityscan-8aed3',
    storageBucket: 'cityscan-8aed3.firebasestorage.app',
    iosClientId: '700781686455-63mrp6k9121t8iaajeuusq1o62hiukf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4RMKIiwCIFep5KUglDIYeOIZYLhLNtU',
    appId: '1:700781686455:ios:282464bc363d421d66e732',
    messagingSenderId: '700781686455',
    projectId: 'cityscan-8aed3',
    storageBucket: 'cityscan-8aed3.firebasestorage.app',
    iosClientId: '700781686455-63mrp6k9121t8iaajeuusq1o62hiukf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoeKIibLVYaIKS4dqIuwD8sf16U51gpuE',
    appId: '1:700781686455:web:747a66059d9b4cd266e732',
    messagingSenderId: '700781686455',
    projectId: 'cityscan-8aed3',
    authDomain: 'cityscan-8aed3.firebaseapp.com',
    storageBucket: 'cityscan-8aed3.firebasestorage.app',
    measurementId: 'G-24NME72CTZ',
  );
}
